### ISSUE TITLE
terraform apply fails on `newrelic_synthetics_multilocation_alert_condition` 

### ISSUE THREAD

**Issue by dehimb** [newrelic/terraform-provider-newrelic#2342]
### Terraform Version
Terraform v1.4.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/http v2.2.0
+ provider registry.terraform.io/newrelic/newrelic v3.20.2

### Affected Resource(s)
- `synthetics_multilocation_alert_condition`

### Terraform Configuration
```hcl
terraform {
  required_version = ">= 1.3.0"
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "3.20.2"
    }
    http = {
      source  = "hashicorp/http"
      version = "~>2"
    }
  }
  backend "http" {}
}

provider "newrelic" {
  alias      = "non_prod"
  account_id = var.nr_account_id_digitech_nonprod
  api_key    = var.nr_api_key_digitech_nonprod
  region     = var.nr_region
}

```

### Actual Behavior
During the apply, provider failing with the next error:
```
newrelic_synthetics_multilocation_alert_condition.example: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to newrelic_synthetics_multilocation_alert_condition.example, provider "provider[\"registry.terraform.io/newrelic/newrelic\"].non_prod" produced
│ an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```
### Expected Behavior
The resource should be created and successfully added to the state

### Steps to Reproduce
I created a simple POC based on example from the documentation

`main.tf`
```hcl
resource "newrelic_alert_policy" "policy" {
  name = "debug-policy"
  provider = newrelic.non_prod
}

resource "newrelic_synthetics_monitor" "monitor" {
  provider = newrelic.non_prod
  locations_public = ["US_WEST_1"]
  name             = "debug-monitor"
  period           = "EVERY_10_MINUTES"
  status           = "DISABLED"
  type             = "SIMPLE"
  uri              = "https://www.one.newrelic.com"
}

resource "newrelic_synthetics_multilocation_alert_condition" "example" {
  provider = newrelic.non_prod
  policy_id = newrelic_alert_policy.policy.id

  name                         = "debug condition"
  runbook_url                  = "https://example.com"
  enabled                      = true
  violation_time_limit_seconds = "3600"

  entities = [
    newrelic_synthetics_monitor.monitor.id
  ]

  critical {
    threshold = 2
  }
}
```

### Debug Output
https://gist.github.com/dehimb/bf5dbb567e41629b335afefd3be0f486

We can see, that request for the creation of the resource finished with 201 Created response
Even if a resource was already created, API did not respond with an error. For each execution, it creates a new alert condition, which leads to duplication.

**Comment by pranav-new-relic** [comment]
Hi @dehimb , thank you for reporting this issue. We've tried reproducing this with the Terraform configuration you've provider (with the same versions of Terraform and the provider), and currently do not find `terraform apply` throwing the error you've described, even upon re-applying after changing a couple of fields in the `synthetics_multilocation_alert_condition` (i.e. upon updating). The API responses to create/update a Synthetics Multilocation Alert Condition also seem to be as expected. Can you please re-check and let us know if you still find the issue persists? Thank you!

**Comment by dehimb** [comment]
Hi,  @pranav-new-relic 
Yes, im still getting the same error
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/652525/234221068-512c0ab3-b8f0-4d24-b929-91d809cc0033.png">

Can this issue be related to the NR account?

**Comment by dehimb** [comment]
Hi, @pranav-new-relic 
From the documentation, we can see that [newrelic_synthetics_multilocation_alert_condition](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/synthetics_multilocation_alert_condition) is deprecated and need to be replaced with [newrelic_nrql_alert_condition](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition)
Are there any examples of how to achieve the same behavior with newrelic_nrql_alert_condition?

**Comment by pranav-new-relic** [comment]
Hi @dehimb - sorry, couldn't reach out to you as we were slightly occupied with a couple of other issues. We recently have had few issues around the NerdGraph API backing resources based on alerts in Terraform, which were addressed sometime ago, and I'd like to see if that would help this issue too, as it seems to be stemming out of the `newrelic_synthetics_multilocation_alert_condition` resource. Can you please give this a try again and let us know if it works? 

I'd need to have a huddle with my team for an idea on moving your configuration in the `newrelic_synthetics_multilocation_alert_condition` to `newrelic_nrql_alert_condition` - will reach back to you on that. Thanks!

**Comment by dehimb** [comment]
Hi, @pranav-new-relic 
Issue is still the same
![image](https://user-images.githubusercontent.com/652525/234810129-90750df9-c318-4705-961f-25b372b7004b.png)

**Comment by pranav-new-relic** [comment]
@dehimb can you please run ```terraform apply``` by setting ```TF_LOG=TRACE``` and attach the trace logs obtained here, so it would help us find the root cause better? Thanks!

**Comment by dehimb** [comment]
Sure, @pranav-new-relic 
https://gist.github.com/dehimb/436aed85aa46d9e39cd8c6ac7abc728e

Also, i discovered one more thing — despite the error, `newrelic_synthetics_multilocation_alert_condition` was created under the hood. I tried to import the to the state but without success — throwing the error that object does not exist. But for old resources import working ok

**Comment by pranav-new-relic** [comment]
Hi @dehimb 
> From the documentation, we can see that [newrelic_synthetics_multilocation_alert_condition](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/synthetics_multilocation_alert_condition) is deprecated and need to be replaced with [newrelic_nrql_alert_condition](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition) Are there any examples of how to achieve the same behavior with newrelic_nrql_alert_condition?

The `newrelic_nrql_alert_condition` equivalent of the `newrelic_synthetics_multilocation_alert_condition` resource is as follows - 
- Replace the attribute **entities** with the following block. 
```  
nrql {
    query = "SELECT count(*) as 'Failures' FROM SyntheticCheck WHERE entityGuid IN ('{monitor.id}') AND result = 'FAILED' FACET monitorName"
}
```
- All other attributes would be the same, as they are supported by `newrelic_nrql_alert_condition`.
- Change the name of the resource to `newrelic_nrql_alert_condition` of course :)

Can you please let me know if this works?

**Comment by pranav-new-relic** [comment]
Alternatively (as suggested by a colleague at New Relic), the procedure to obtain Terraform code for the condition as a `newrelic_nrql_alert_condition` from the New Relic UI is as follows - though this is not certainly a replica of the `multilocation_alert_condition` as an `nrql_alert_condition`, you can give this a try.

- Visit New Relic One > Alerts & AI > Alert Conditions (Policies) > New Alert Condition
- Select "Golden Signal or Metric" > Synthetic Monitors
- Select the Synthetic Monitor you've created via the configuration (i.e. "debug-monitor" in this case).
- Under "Select a signal to monitor", select "Failures" and click "Next".
- In the "Adjust to Signal Behaviour" section, change options as required and click "Next".
- In the "Define Thresholds" section, change/add warning/critical thresholds as required and click "Next".
- In the "Add alert condition details" section, add a name to the condition, select the created policy from the dropdown and configure other settings such as "Close open incidents after" (violation time limit - 3600 seconds is one hour) and "Runbook URL". Click on "Save Condition".
- In the next section, find the "View Code In" button, and select "View" under Terraform. You will now find code with the resource `newrelic_nrql_alert_condition` which may be modified as required.

**Comment by nunofernandes** [comment]
I'm also having the same issue:
```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to newrelic_synthetics_multilocation_alert_condition.xyz, provider "provider[\"registry.terraform.io/newrelic/newrelic\"]" produced an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

```

**Comment by pranav-new-relic** [comment]
@nunofernandes can you please attach logs you find when you run `terraform apply` by setting `TF_LOG=TRACE`? This would help us look further into the issue.

**Comment by dehimb** [comment]
Hello, @pranav-new-relic @NSSPKrishna 

I tried several approaches with NRQL queries and can confirm that the query itself working as expected. For the multilocation check, i used the next query
`SELECT uniqueCount(locationLabel) FROM SyntheticCheck WHERE entityGuid = '%s' AND result = 'FAILED'`

But there is a big problem — as far as the aggregation window should be the same as the frequency of synthetic checks(30 minutes, for example), the delay of the alert trigger could be up to this window length(30 minutes in my case). The same for issue closing delay, when synthetic is back to normal. We can't use this approach, because we need to be alerted as soon as checks for two locations failed.

**Comment by pranav-new-relic** [comment]
Hi @dehimb, thanks for trying this out - from what you're saying, it looks like the `newrelic_nrql_alert_condition` resource currently has inadequate backing to be able to exactly replicate a `newrelic_synthetics_multilocation_alert_condition`, which I think the concerned team is working on.

As I mentioned previously - we're having a hard time reproducing the issue you've mentioned with the `multilocation_alert_condition` - we'll see what can be done about this to identify the cause. Thanks.

**Comment by nunofernandes** [comment]
Hi @pranav-new-relic , 

I'm not comfortable sharing the trace file in the public but I can send that over to some @newrelic.com email or publish that through a support case in New Relic... :pray:

**Comment by pranav-new-relic** [comment]
@nunofernandes please mail it to pnandula@newrelic.com

**Comment by nunofernandes** [comment]
@pranav-new-relic  was just sent..

**Comment by pranav-new-relic** [comment]
@nunofernandes received, thanks. Will take a look

**Comment by pranav-new-relic** [comment]
@dehimb a quick question - 

> I tried several approaches with NRQL queries and can confirm that the query itself working as expected. For the multilocation check, i used the next query `SELECT uniqueCount(locationLabel) FROM SyntheticCheck WHERE entityGuid = '%s' AND result = 'FAILED'`
> 
> But there is a big problem — as far as the aggregation window should be the same as the frequency of synthetic checks(30 minutes, for example), the delay of the alert trigger could be up to this window length(30 minutes in my case). The same for issue closing delay, when synthetic is back to normal. We can't use this approach, because we need to be alerted as soon as checks for two locations failed.

This looks like you tried constructing an NRQL query that would fit into a `newrelic_nrql_alert_condition` - however, did you try setting up the condition via the UI and then using the Terraform Configuration (with the condition as a `newrelic_nrql_alert_condition`) shown in the UI, using the procedure specified above?

> Alternatively (as suggested by a colleague at New Relic), the procedure to obtain Terraform code for the condition as a `newrelic_nrql_alert_condition` from the New Relic UI is as follows - though might probably not be an exact replica of the `multilocation_alert_condition` as an `nrql_alert_condition`, you can give this a try.
> 
> * Visit New Relic One > Alerts & AI > Alert Conditions (Policies) > New Alert Condition
> * Select "Golden Signal or Metric" > Synthetic Monitors
> * Select the Synthetic Monitor you've created via the configuration (i.e. "debug-monitor" in this case).
> * Under "Select a signal to monitor", select "Failures" and click "Next".
> * In the "Adjust to Signal Behaviour" section, change options as required and click "Next".
> * In the "Define Thresholds" section, change/add warning/critical thresholds as required and click "Next".
> * In the "Add alert condition details" section, add a name to the condition, select the created policy from the dropdown and configure other settings such as "Close open incidents after" (violation time limit - 3600 seconds is one hour) and "Runbook URL". Click on "Save Condition".
> * In the next section, find the "View Code In" button, and select "View" under Terraform. You will now find code with the resource `newrelic_nrql_alert_condition` which may be modified as required.

Just wanted to check with you, as the Terraform Code shown in the UI would (maybe) help address the concern you've mentioned about the aggregation window and the delay, as the UI procedure would help include these specifications in the Terraform Configuration too. Please ignore if it doesn't work that way too.

Meanwhile, we shall try looking into this issue further - we've some additional inputs from @nunofernandes that could help us.

**Comment by dehimb** [comment]
Hi, @pranav-new-relic 
Yes, i tried the mentioned procedure, and the code is similar to what i used for the tests. From the UI, we are specifying an aggregation window, and for the correct behavior, it should be the same, as the execution period of the synthetic check(to confirm two failed locations). So, the problem is the same

**Comment by pranav-new-relic** [comment]
Hi, a quick update - we've been able to reproduce this issue recently (unlike as previously mentioned with @dehimb in this thread), and identified this is an issue with the API that is failing to fetch the created multilocation_alert_conditon (though it succeeds to be created), leading to the error in Terraform. The same is happening when you explicitly try importing the created multilocation_alert_condition, owing to the same issue.

We've got in touch with the concerned team, who have acknowledged the issue with the API, and will soon plan on working on its fix. I shall keep you posted once the fix is out - thank you.

**Comment by pranav-new-relic** [comment]
Hi @dehimb @nunofernandes looks like the fix is out - I've tried reproducing the issue again and I don't find it recurring (the `newrelic_synthetics_multilocation_alert_condition` seems to be created successfully, with no error in Terraform). Can you please give this a try again and let me know if this is the case with you too? Thanks.

**Comment by vinodkumar4** [comment]
Hi @pranav-new-relic which version of Terraform/NewRelic fixes this now ?

**Comment by pranav-new-relic** [comment]
Sorry, did not specify this above - please try with v3.22.0, the recently released version.

**Comment by dehimb** [comment]
Hi, @pranav-new-relic 
I can confirm, that the issue is resolved. All our pipelines working as expected.

Thanks for cooperation

**Comment by pranav-new-relic** [comment]
Cool, glad to know :)

**Comment by nunofernandes** [comment]
Hi, @pranav-new-relic , 

I can also confirm that the issue is resolved! 

Thank you so much!

**Comment by pranav-new-relic** [comment]
@nunofernandes thanks, that's great news :)
