### ISSUE TITLE
alert condition seems to be unable to be configured to alert if something is greater than zero

### ISSUE THREAD

**Issue by timothy-spencer** [newrelic/terraform-provider-newrelic#740]
### Terraform Version
0.12.24

### Affected Resource(s)
- newrelic_nrql_alert_condition

### Terraform Configuration Files
```hcl
provider "newrelic" {
  version = ">= 2.1.2"
  region = "US"
}

variable "opsgenie_api_key" {}
variable "env_name" {}
variable "region" {
  default = "us-west-2"
}

resource "newrelic_alert_channel" "opsgenie" {
  name = "opsgenie-channel-${var.env_name}"
  type = "opsgenie"

  config {
    api_key    = var.opsgenie_api_key
    tags       = var.env_name
    region     = "US"
  }
}

resource "newrelic_alert_policy_channel" "high" {
  policy_id  = newrelic_alert_policy.high.id
  channel_ids = [
    newrelic_alert_channel.opsgenie.id
  ]
}

# This one works
resource "newrelic_nrql_alert_condition" "no_es_metrics" {
  policy_id = newrelic_alert_policy.high.id
  name        = "${var.env_name}_es_no_metrics"
  description = "Alert when there are no metrics coming from the ${var.env_name} ES cluster"
  enabled     = true
  value_function = "single_value"
  violation_time_limit = "TWELVE_HOURS"

  nrql {
    query       = "SELECT count(*) from ElasticSearchHealthSample where label.environment = '${var.env_name}'"
    evaluation_offset = 3
  }

  critical {
    operator              = "below"
    threshold             = 1
    threshold_duration    = 300
    threshold_occurrences = "AT_LEAST_ONCE"
  }
}

# This one does not
resource "newrelic_nrql_alert_condition" "no_logstash_metrics" {
  policy_id = newrelic_alert_policy.high.id
  name        = "${var.env_name}_ls_no_metrics"
  description = "Alert when there are no metrics coming from the ${var.env_name} logstash host: logstash host may be down"
  enabled     = true
  value_function = "single_value"
  violation_time_limit = "TWELVE_HOURS"

  nrql {
    query       = "SELECT count(*) from LogstashHealthSample where label.environment = '${var.env_name}'"
    evaluation_offset = 3
  }

  critical {
    operator              = "above"
    threshold             = 0
    threshold_duration    = 300
    threshold_occurrences = "AT_LEAST_ONCE"
  }
}
```

### Debug Output
```
Error: Argument "condition" has invalid value $condition.
In field "terms": Expected type "[AlertsNrqlConditionTermsInput!]", found [{operator: "ABOVE", priority: "CRITICAL", thresholdDuration: 300, thresholdOccurrences: "AT_LEAST_ONCE"}].
In element #1: Expected type "AlertsNrqlConditionTermsInput", found {operator: "ABOVE", priority: "CRITICAL", thresholdDuration: 300, thresholdOccurrences: "AT_LEAST_ONCE"}.
In field "threshold": Expected type "Float!", found null., null

  on ../modules/newrelic/main.tf line 228, in resource "newrelic_nrql_alert_condition" "no_logstash_metrics":
 228: resource "newrelic_nrql_alert_condition" "no_logstash_metrics" {
```

### Panic Output
None

### Expected Behavior
I should be able to set an alert condition that triggers on the metric being above zero.  The inverse works, setting an alert condition such that it alerts on the metric being below 1, so I would imagine that an above zero check would work too.

### Actual Behavior
The plugin says that condition has an invalid value (see debug output above) and errors out.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Fill out variables
1. `terraform apply`

### Important Factoids
I really can't plug the full debug info in because it seems to have all sorts of keys and things.  But if the error output is not enough, let me know, and I can struggle with sanitizing.

Also, the HCL above has been extracted and somewhat sanitized from a much larger terraform deployment, and I _think_ it should work, but it's hard for me to just do it standalone, so apologies if I forgot something!

### References
I didn't find any.

**Comment by zlesnr** [comment]
Hi, thank you for reporting the issue.  I suspect that its' just that the threshold is set to `0`.  Anything other than specifically `0` should work.  Would using something like `0.00001` work for this use case?

**Comment by timothy-spencer** [comment]
I will have to set things up to where I can try it again later, but isn't 0 a valid value in there?  Why wouldn't it work?  If zero is an invalid value, then maybe that could be made more clear in the docs or in the error message?

**Comment by zlesnr** [comment]
Zero isn't a valid option there I believe because the current version of the Terraform SDK that's in use here isn't able to distinguish between "not set" and set to the zero-value of the go type.  We can probably revisit this when we get moving to the newer Terraform SDK.

I agree about the docs, and I've got an update pending in #741 that should clarify.  I'll double check my assumptions here, but I believe that's the case currently.

**Comment by timothy-spencer** [comment]
Cool.  Well, I have my workaround:  trigger if it's below 1 rather than above 0.  I just thought it was a bug, because they logically seem like they should both work, and the error message was not very helpful.  Thanks for your help, and have fun!

**Comment by zlesnr** [comment]
I tend to agree with you.  I'm sure we'll be revisiting what nil means after an SDK update.

**Comment by zlesnr** [comment]
This came up again today, and my teammate looked closer at it.  I was wrong about the SDK update here, and it looks like we just need to remove the `omitempty` field tag and this will probably work.  I'll get a release out here shortly to address and close this issue out as part of that work.  My apologies for the bad information earlier.

**Comment by zlesnr** [comment]
https://github.com/newrelic/newrelic-client-go/pull/372#event-3507929873

**Comment by ctrombley** [comment]
This was resolved in v2.2.0 of the provider.  @timothy-spencer please let us know if you are still running into issues after upgrading.

**Comment by trunet** [comment]
> This was resolved in v2.2.0 of the provider. @timothy-spencer please let us know if you are still running into issues after upgrading.

I'm on 2.2.1, I'm still facing this problem. threshold = 0 doesn't work

**Comment by trunet** [comment]
2.3.0 fixed the threshold = 0. working for me.

**Comment by zlesnr** [comment]
I believe this has been resolved.  Feel-free to reopen if there are further troubles.
